package com.ryanworks.fishery.client.ui.control;

import com.ryanworks.fishery.client.delegate.SystemDataDelegate;
import com.ryanworks.fishery.client.ui.control.listener.ItemEditorDialogListener;
import com.ryanworks.fishery.shared.bean.CategoryBean;
import com.ryanworks.fishery.shared.bean.ItemBean;
import com.ryanworks.fishery.shared.swing.listener.JTextFieldFocusListener;
import java.text.DecimalFormat;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author Ryan C
 */
public class ItemEditorDialog 
    extends javax.swing.JDialog 
{
    public final static int EDITOR_MODE_NEW     = 1;
    public final static int EDITOR_MODE_EDIT    = 2;
    
    private final DecimalFormat twoPlacesFormatter = new DecimalFormat("0.00");
    
    private int editingMode;
    private ItemBean itemObj;
    private final ItemEditorDialogListener listener;
    private String itemCategory;
    
    /**
     * Creates new form ItemEditorDialog
     * @param parent
     * @param modal
     * @param listener
     * @param itemBean
     */
    public ItemEditorDialog(java.awt.Frame parent, boolean modal, ItemEditorDialogListener listener, ItemBean itemBean, String itemCategory) 
    {
        super(parent, modal);
        this.itemObj = itemBean;
        this.listener = listener;
        this.itemCategory = itemCategory;
        
        initComponents();
        myInit();
    }
    
    private void myInit()
    {
        if (this.itemObj == null)
        {
            this.editingMode = EDITOR_MODE_NEW;
            this.itemObj = new ItemBean();
        }
        else
        {
            this.editingMode = EDITOR_MODE_EDIT;
        }
        
        int selectedCategory = 0, i=0;
        List<CategoryBean> categoryList = SystemDataDelegate.getInstance().getAllCategories();
        for (CategoryBean category : categoryList)
        {
            this.jComboBoxCategory.addItem(category);
            if (category.getName().equals(itemCategory))
                selectedCategory = i;
            i++;
        }
        this.jComboBoxCategory.setSelectedIndex(selectedCategory);
        
        System.err.println("itemCategory="+itemCategory);
        System.err.println("selectedCategory="+selectedCategory);
        
        this.jTextFieldName.addFocusListener( new JTextFieldFocusListener() );
        this.jTextFieldNameBm.addFocusListener( new JTextFieldFocusListener() );
        this.jTextFieldPrice.addFocusListener( new JTextFieldFocusListener() );
        
        this.fillForm();
    }

    private void fillForm()
    {
        if (this.editingMode == ItemEditorDialog.EDITOR_MODE_NEW)
        {
            this.jTextFieldId.setText( this.itemObj.getId() );
            this.jComboBoxCategory.setSelectedIndex(0);
        }
        else
        if (this.editingMode == ItemEditorDialog.EDITOR_MODE_EDIT)
        {
            for (int i=0 ; i<this.jComboBoxCategory.getItemCount() ; i++)
            {
                if (((CategoryBean)this.jComboBoxCategory.getItemAt(i)).getId().equalsIgnoreCase( this.itemObj.getCategoryId() ) )
                {
                    this.jComboBoxCategory.setSelectedIndex(i);
                    break;
                }
            }
            
            this.jTextFieldId.setText( this.itemObj.getId() );
            this.jTextFieldName.setText( this.itemObj.getName() );
            this.jTextFieldNameBm.setText( this.itemObj.getNameBm() );
            this.jTextFieldPrice.setText( twoPlacesFormatter.format( this.itemObj.getPrice() ) );
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldId = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldName = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldPrice = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jComboBoxCategory = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldNameBm = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jButtonOk = new javax.swing.JButton();
        jButtonCancel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(0, 153, 255));

        jLabel1.setFont(new java.awt.Font("KaiTi", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("海春鱼行");
        jPanel1.add(jLabel1);

        getContentPane().add(jPanel1, java.awt.BorderLayout.NORTH);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "鱼类", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("KaiTi", 0, 18))); // NOI18N

        jLabel2.setFont(new java.awt.Font("KaiTi", 0, 18)); // NOI18N
        jLabel2.setText("ID:");

        jTextFieldId.setEditable(false);
        jTextFieldId.setFont(new java.awt.Font("KaiTi", 0, 18)); // NOI18N

        jLabel3.setFont(new java.awt.Font("KaiTi", 0, 18)); // NOI18N
        jLabel3.setText("鱼类名字:");

        jTextFieldName.setFont(new java.awt.Font("KaiTi", 0, 18)); // NOI18N
        jTextFieldName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNameActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("KaiTi", 0, 18)); // NOI18N
        jLabel5.setText("单位价格：");

        jTextFieldPrice.setFont(new java.awt.Font("KaiTi", 0, 18)); // NOI18N
        jTextFieldPrice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldPriceActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("KaiTi", 0, 18)); // NOI18N
        jLabel6.setText("鱼类类别:");

        jComboBoxCategory.setFont(new java.awt.Font("KaiTi", 0, 18)); // NOI18N

        jLabel4.setFont(new java.awt.Font("KaiTi", 0, 18)); // NOI18N
        jLabel4.setText("马来名字:");

        jTextFieldNameBm.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTextFieldNameBm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNameBmActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel6))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addComponent(jTextFieldId))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jComboBoxCategory, 0, 249, Short.MAX_VALUE))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addComponent(jLabel3))
                            .addComponent(jLabel5))
                        .addGap(10, 10, 10)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldPrice, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jTextFieldName)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(19, 19, 19)
                        .addComponent(jTextFieldNameBm)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextFieldId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jComboBoxCategory, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTextFieldNameBm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2, java.awt.BorderLayout.CENTER);

        jButtonOk.setFont(new java.awt.Font("KaiTi", 0, 18)); // NOI18N
        jButtonOk.setText("确定");
        jButtonOk.setPreferredSize(new java.awt.Dimension(100, 29));
        jButtonOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOkActionPerformed(evt);
            }
        });
        jPanel3.add(jButtonOk);

        jButtonCancel.setFont(new java.awt.Font("KaiTi", 0, 18)); // NOI18N
        jButtonCancel.setText("取消");
        jButtonCancel.setPreferredSize(new java.awt.Dimension(100, 29));
        jButtonCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelActionPerformed(evt);
            }
        });
        jPanel3.add(jButtonCancel);

        getContentPane().add(jPanel3, java.awt.BorderLayout.SOUTH);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOkActionPerformed
        try 
        {
            if (this.jTextFieldName.getText().trim().length() ==0)
            {
                this.jTextFieldName.requestFocus();
                this.jTextFieldName.selectAll();

                JOptionPane.showMessageDialog(
                        this, 
                        "Invalid 'Name' format. Please insert a valid name.", 
                        "Invalid Input", 
                        JOptionPane.ERROR_MESSAGE);
                
                return;
            }
            
            if (this.jTextFieldPrice.getText().trim().length() ==0)
            {
                this.jTextFieldPrice.requestFocus();
                this.jTextFieldPrice.selectAll();

                JOptionPane.showMessageDialog(
                        this, 
                        "Invalid 'Price' format. Please insert a valid price.", 
                        "Invalid Input", 
                        JOptionPane.ERROR_MESSAGE);
                
                return;
            }
            
            this.itemObj.setName(this.jTextFieldName.getText().trim());
            this.itemObj.setNameBm(this.jTextFieldNameBm.getText().trim());
            this.itemObj.setPrice(Double.parseDouble(this.jTextFieldPrice.getText().trim()));
            this.itemObj.setCategoryId(((CategoryBean)this.jComboBoxCategory.getSelectedItem()).getId());
            
            this.listener.itemEditorDialogClosed( this.itemObj );
            this.setVisible( false );
            this.dispose();
        }
        catch (NumberFormatException e)
        {
            this.jTextFieldPrice.requestFocus();
            this.jTextFieldPrice.selectAll();
            
            JOptionPane.showMessageDialog(
                    this, 
                    "Invalid 'Price' format. Must be decimal value.", 
                    "Invalid Input", 
                    JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButtonOkActionPerformed

    private void jButtonCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelActionPerformed
       this.setVisible( false );
       this.dispose();
    }//GEN-LAST:event_jButtonCancelActionPerformed

    private void jTextFieldNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNameActionPerformed
        this.jTextFieldNameBm.requestFocus();
        this.jTextFieldNameBm.selectAll();
    }//GEN-LAST:event_jTextFieldNameActionPerformed

    private void jTextFieldPriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldPriceActionPerformed
        this.jButtonOk.doClick();
    }//GEN-LAST:event_jTextFieldPriceActionPerformed

    private void jTextFieldNameBmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNameBmActionPerformed
        this.jTextFieldPrice.requestFocus();
        this.jTextFieldPrice.selectAll();
    }//GEN-LAST:event_jTextFieldNameBmActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCancel;
    private javax.swing.JButton jButtonOk;
    private javax.swing.JComboBox jComboBoxCategory;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField jTextFieldId;
    private javax.swing.JTextField jTextFieldName;
    private javax.swing.JTextField jTextFieldNameBm;
    private javax.swing.JTextField jTextFieldPrice;
    // End of variables declaration//GEN-END:variables
}
