package com.ryanworks.fishery.client.ui.control;

import com.ryanworks.fishery.client.ui.control.listener.SupplierEditorDialogListener;
import com.ryanworks.fishery.shared.bean.SupplierBean;
import com.ryanworks.fishery.shared.swing.listener.JTextAreaFocusListener;
import com.ryanworks.fishery.shared.swing.listener.JTextFieldFocusListener;
import java.text.DecimalFormat;
import javax.swing.JOptionPane;

/**
 *
 * @author Ryan C
 */
public class SupplierEditorDialog 
    extends javax.swing.JDialog 
{
    public final static int EDITOR_MODE_NEW     = 1;
    public final static int EDITOR_MODE_EDIT    = 2;
    
    private final DecimalFormat twoPlacesFormatter = new DecimalFormat("0.00");
    
    private int editingMode;
    private SupplierBean supplierObj;
    private final SupplierEditorDialogListener listener;
    
    /**
     * Creates new form ItemEditorDialog
     * @param parent
     * @param modal
     * @param listener
     * @param supplierBean
     */
    public SupplierEditorDialog(java.awt.Frame parent, boolean modal, SupplierEditorDialogListener listener, SupplierBean supplierBean) 
    {
        super(parent, modal);
        this.supplierObj = supplierBean;
        this.listener = listener;
        
        initComponents();
        myInit();
    }
    
    private void myInit()
    {
        if (this.supplierObj == null)
        {
            this.editingMode = EDITOR_MODE_NEW;
            this.supplierObj = new SupplierBean();  
            this.jTextFieldId.addFocusListener( new JTextFieldFocusListener() );          
        }
        else
        {
            this.editingMode = EDITOR_MODE_EDIT;
        }
        
        
        this.jTextFieldName.addFocusListener( new JTextFieldFocusListener() );
        this.jTextFieldPercentage.addFocusListener( new JTextFieldFocusListener() );
        this.jTextAreaNotes.addFocusListener( new JTextAreaFocusListener() );
        
        this.fillForm();
    }

    private void fillForm()
    {
        if (this.editingMode == SupplierEditorDialog.EDITOR_MODE_NEW)
        {
            this.jTextFieldId.setEditable(true);
            this.jTextFieldId.setText( this.supplierObj.getId() );
            this.jTextFieldId.requestFocus();
            this.jTextFieldId.selectAll();
        }
        else
        if (this.editingMode == SupplierEditorDialog.EDITOR_MODE_EDIT)
        {
            this.jTextFieldId.setEditable(false);            
            this.jTextFieldId.setText( this.supplierObj.getId() );
            this.jTextFieldName.setText( this.supplierObj.getName() );
            this.jTextFieldNumber.setText( this.supplierObj.getShipNumber() );
            this.jCheckBoxFrequent.setSelected( this.supplierObj.isFrequent() );
            this.jCheckBoxSavingAccount.setSelected( this.supplierObj.isSavingAccount());
            this.jTextFieldPercentage.setText( twoPlacesFormatter.format( this.supplierObj.getPercentage()) );
            this.jTextAreaNotes.setText( this.supplierObj.getNotes() );
            
            this.jTextFieldName.requestFocus();
            this.jTextFieldName.selectAll();
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldId = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldName = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldPercentage = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaNotes = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldNumber = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jCheckBoxSavingAccount = new javax.swing.JCheckBox();
        jLabel8 = new javax.swing.JLabel();
        jCheckBoxFrequent = new javax.swing.JCheckBox();
        jPanel3 = new javax.swing.JPanel();
        jButtonOk = new javax.swing.JButton();
        jButtonCancel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(0, 153, 255));

        jLabel1.setFont(new java.awt.Font("KaiTi", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("海春鱼行");
        jPanel1.add(jLabel1);

        getContentPane().add(jPanel1, java.awt.BorderLayout.NORTH);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "船户资料", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("KaiTi", 0, 18))); // NOI18N

        jLabel2.setFont(new java.awt.Font("KaiTi", 0, 18)); // NOI18N
        jLabel2.setText("ID:");

        jTextFieldId.setEditable(false);
        jTextFieldId.setFont(new java.awt.Font("KaiTi", 0, 18)); // NOI18N

        jLabel3.setFont(new java.awt.Font("KaiTi", 0, 18)); // NOI18N
        jLabel3.setText("船户名字:");

        jTextFieldName.setFont(new java.awt.Font("KaiTi", 0, 18)); // NOI18N
        jTextFieldName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNameActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("KaiTi", 0, 18)); // NOI18N
        jLabel5.setText("回扣巴仙：");

        jTextFieldPercentage.setFont(new java.awt.Font("KaiTi", 0, 18)); // NOI18N
        jTextFieldPercentage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldPercentageActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("KaiTi", 0, 18)); // NOI18N
        jLabel7.setText("其他:");

        jTextAreaNotes.setColumns(20);
        jTextAreaNotes.setRows(5);
        jScrollPane1.setViewportView(jTextAreaNotes);

        jLabel4.setFont(new java.awt.Font("KaiTi", 0, 18)); // NOI18N
        jLabel4.setText("船户号码:");

        jTextFieldNumber.setFont(new java.awt.Font("KaiTi", 0, 18)); // NOI18N
        jTextFieldNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNumberActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("KaiTi", 0, 18)); // NOI18N
        jLabel6.setText("有储蓄:");

        jLabel8.setFont(new java.awt.Font("KaiTi", 0, 18)); // NOI18N
        jLabel8.setText("经常来:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(73, 73, 73)
                        .addComponent(jTextFieldId, javax.swing.GroupLayout.DEFAULT_SIZE, 248, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(55, 55, 55)
                        .addComponent(jScrollPane1))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(19, 19, 19)
                        .addComponent(jTextFieldNumber))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextFieldPercentage))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(19, 19, 19)
                        .addComponent(jTextFieldName))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel6))
                        .addGap(37, 37, 37)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jCheckBoxSavingAccount)
                            .addComponent(jCheckBoxFrequent))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextFieldId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTextFieldNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextFieldName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(jCheckBoxFrequent))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel6)
                    .addComponent(jCheckBoxSavingAccount))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldPercentage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(106, 106, 106))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );

        getContentPane().add(jPanel2, java.awt.BorderLayout.CENTER);

        jButtonOk.setFont(new java.awt.Font("KaiTi", 0, 18)); // NOI18N
        jButtonOk.setText("确定");
        jButtonOk.setPreferredSize(new java.awt.Dimension(100, 29));
        jButtonOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOkActionPerformed(evt);
            }
        });
        jPanel3.add(jButtonOk);

        jButtonCancel.setFont(new java.awt.Font("KaiTi", 0, 18)); // NOI18N
        jButtonCancel.setText("取消");
        jButtonCancel.setPreferredSize(new java.awt.Dimension(100, 29));
        jButtonCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelActionPerformed(evt);
            }
        });
        jPanel3.add(jButtonCancel);

        getContentPane().add(jPanel3, java.awt.BorderLayout.SOUTH);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOkActionPerformed
        try 
        {
            if (this.jTextFieldName.getText().trim().length() ==0)
            {
                this.jTextFieldName.requestFocus();
                this.jTextFieldName.selectAll();

                JOptionPane.showMessageDialog(
                        this, 
                        "Invalid 'Name' format. Please insert a valid name.", 
                        "Invalid Input", 
                        JOptionPane.ERROR_MESSAGE);
                
                return;
            }
            
            if (this.jTextFieldPercentage.getText().trim().length() ==0)
            {
                this.jTextFieldPercentage.requestFocus();
                this.jTextFieldPercentage.selectAll();

                JOptionPane.showMessageDialog(
                        this, 
                        "Invalid 'Percentage' format. Please insert a valid percentage.", 
                        "Invalid Input", 
                        JOptionPane.ERROR_MESSAGE);
                
                return;
            }
            
            this.supplierObj.setName(this.jTextFieldName.getText().trim());
            this.supplierObj.setShipNumber(this.jTextFieldNumber.getText().trim());
            this.supplierObj.setFrequent(this.jCheckBoxFrequent.isSelected());
            this.supplierObj.setSavingAccount(this.jCheckBoxSavingAccount.isSelected());
            this.supplierObj.setPercentage(Double.parseDouble(this.jTextFieldPercentage.getText().trim()));
            this.supplierObj.setNotes(this.jTextAreaNotes.getText().trim());
            
            this.listener.supplierEditorDialogClosed( this.supplierObj );
            this.setVisible( false );
            this.dispose();
        }
        catch (NumberFormatException e)
        {
            this.jTextFieldPercentage.requestFocus();
            this.jTextFieldPercentage.selectAll();
            
            JOptionPane.showMessageDialog(
                    this, 
                    "Invalid 'Percentage' format. Must be decimal value.", 
                    "Invalid Input", 
                    JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButtonOkActionPerformed

    private void jButtonCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelActionPerformed
       this.setVisible( false );
       this.dispose();
    }//GEN-LAST:event_jButtonCancelActionPerformed

    private void jTextFieldNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNameActionPerformed
        this.jTextFieldPercentage.requestFocus();
        this.jTextFieldPercentage.selectAll();
    }//GEN-LAST:event_jTextFieldNameActionPerformed

    private void jTextFieldPercentageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldPercentageActionPerformed
        this.jButtonOk.doClick();
    }//GEN-LAST:event_jTextFieldPercentageActionPerformed

    private void jTextFieldNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNumberActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCancel;
    private javax.swing.JButton jButtonOk;
    private javax.swing.JCheckBox jCheckBoxFrequent;
    private javax.swing.JCheckBox jCheckBoxSavingAccount;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextAreaNotes;
    private javax.swing.JTextField jTextFieldId;
    private javax.swing.JTextField jTextFieldName;
    private javax.swing.JTextField jTextFieldNumber;
    private javax.swing.JTextField jTextFieldPercentage;
    // End of variables declaration//GEN-END:variables
}
