package com.ryanworks.fishery.client.ui;

import com.ryanworks.fishery.client.print.InboundPDFBoxPrinter;
import com.ryanworks.fishery.client.print.OutboundPDFBoxPrinter;
import com.ryanworks.fishery.client.ui.control.ControlPanel;
import com.ryanworks.fishery.client.ui.inbound.InboundStockingPanel;
import com.ryanworks.fishery.client.ui.outbound.OutboundSalesPanel;
import com.ryanworks.fishery.shared.util.MyLogger;
import java.awt.CardLayout;
import javax.swing.JFrame;
import javax.swing.WindowConstants;

/**
 *
 * @author Ryan C
 */
public class JFrameMain extends javax.swing.JFrame {

    private final static String LOGIN_SCREEN_NAME = "loginScreen";
    private final static String MAIN_SCREEN_NAME = "mainScreen";
    private final static String SCREEN_CONTROL = "controlScreen";
    private final static String SCREEN_INBOUND = "inboundScreen";
    private final static String SCREEN_OUTBOUND = "outboundScreen";
    
    private LoginPanel jPanelLogin;
    private MainPanel jPanelMain;
    private InboundStockingPanel jPanelInboundMainScreen;
    private OutboundSalesPanel jPanelOutboundMainScreen;
    private ControlPanel jPanelControl;
    
    /**
     * Creates new form JFrameMain
     */
    public JFrameMain() 
    {
        initComponents();
        myInit();   
    }
    
    private void myInit() 
    {        
        //jPanelLogin = new LoginPanel(this, LoginPanel.MAIN_SCREEN);
        jPanelInboundMainScreen = new InboundStockingPanel(this);
        jPanelOutboundMainScreen = new OutboundSalesPanel(this);
        jPanelMain = new MainPanel(this);
        jPanelControl = new ControlPanel(this);
     
        //this.jPanelCards.add(jPanelLogin, LOGIN_SCREEN_NAME);
        this.jPanelCards.add(jPanelMain, MAIN_SCREEN_NAME);
        this.jPanelCards.add(jPanelInboundMainScreen, SCREEN_INBOUND);
        this.jPanelCards.add(jPanelOutboundMainScreen, SCREEN_OUTBOUND);
        this.jPanelCards.add(jPanelControl, SCREEN_CONTROL);
        
        // Set Application default close action
        this.setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);
        
        // Maximize screen
        this.setExtendedState(this.getExtendedState()|JFrame.MAXIMIZED_BOTH);
        
        // Set focus back to login pane
        //this.jPanelLogin.resetFocusState();
        
        InboundPDFBoxPrinter.getInstance().init();
        OutboundPDFBoxPrinter.getInstance().init();
    }

    /*
    public void switchToLoginPanel() {
        CardLayout cardLayout = (CardLayout) this.jPanelCards.getLayout();
        cardLayout.show(this.jPanelCards, LOGIN_SCREEN_NAME);
        
        //this.jPanelLogin.resetFocusState();
    }*/
    
    public void switchToMainPanel() 
    {
        CardLayout cardLayout = (CardLayout) this.jPanelCards.getLayout();
        cardLayout.show(this.jPanelCards, MAIN_SCREEN_NAME);
    }
    
    public void switchToControlPanel() 
    {
        jPanelControl.setActive(true);
        CardLayout cardLayout = (CardLayout) this.jPanelCards.getLayout();
        cardLayout.show(this.jPanelCards, SCREEN_CONTROL);
    }
    
    public InboundStockingPanel switchToInboundPanel() 
    {
        this.jPanelInboundMainScreen.reset();
        
        CardLayout cardLayout = (CardLayout) this.jPanelCards.getLayout();
        cardLayout.show(this.jPanelCards, SCREEN_INBOUND);
        
        return this.jPanelInboundMainScreen;
    }
    
    public OutboundSalesPanel switchToOutboundPanel() 
    {
        this.jPanelOutboundMainScreen.reset();
        
        CardLayout cardLayout = (CardLayout) this.jPanelCards.getLayout();
        cardLayout.show(this.jPanelCards, SCREEN_OUTBOUND);
        
        return this.jPanelOutboundMainScreen;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelCards = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jPanelCards.setLayout(new java.awt.CardLayout());
        getContentPane().add(jPanelCards, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        MyLogger.logInfo(getClass(), "Closing Application.");
        jPanelInboundMainScreen.closing();
        jPanelOutboundMainScreen.closing();
    }//GEN-LAST:event_formWindowClosing

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrameMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrameMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrameMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrameMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrameMain().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanelCards;
    // End of variables declaration//GEN-END:variables
}
