package com.ryanworks.fishery.client.ui;

import com.ryanworks.fishery.client.delegate.UserDelegate;
import com.ryanworks.fishery.client.ui.shared.ProgressModalDialog;
import com.ryanworks.fishery.shared.bean.UserBean;
import com.ryanworks.fishery.shared.swing.listener.JPasswordFieldFocusListener;
import com.ryanworks.fishery.shared.swing.listener.JTextFieldFocusListener;
import com.ryanworks.fishery.shared.util.SwingUtil;
import java.awt.Toolkit;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.SwingWorker;

/**
 *
 * @author Ryan C
 */
public class LoginPanel 
    extends javax.swing.JPanel 
{
    public final static int MAIN_SCREEN = 1;
    
    private final JFrame parent;
    private UserBean user;
    private final int currentScreen;
    
    /**
     * Creates new form JPanelLogin
     * @param parent
     * @param screen
     */
    public LoginPanel(JFrame parent, int screen) 
    {
        this.parent = parent;
        this.currentScreen = screen;
        
        initComponents();
        myInit();
    }

    private void myInit() 
    {        
        this.jTextFieldUsername.addFocusListener(new JTextFieldFocusListener());
        this.jPasswordField.addFocusListener(new JPasswordFieldFocusListener());
        
        System.out.println("JPanelLogin:myInit() called");
        resetFocusState();
    }
    
    public void resetFocusState() 
    {
        this.jTextFieldUsername.requestFocus();   
        this.user = null;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelTitle = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabelUsername = new javax.swing.JLabel();
        jTextFieldUsername = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabelPassword = new javax.swing.JLabel();
        jPasswordField = new javax.swing.JPasswordField();
        jLabel10 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jButtonLogin = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();

        setLayout(new java.awt.BorderLayout());

        jLabelTitle.setBackground(new java.awt.Color(0, 0, 153));
        jLabelTitle.setFont(new java.awt.Font("KaiTi", 1, 60)); // NOI18N
        jLabelTitle.setForeground(new java.awt.Color(255, 255, 255));
        jLabelTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelTitle.setText("海春鱼行登入系统");
        jLabelTitle.setOpaque(true);
        jLabelTitle.setPreferredSize(new java.awt.Dimension(408, 120));
        add(jLabelTitle, java.awt.BorderLayout.PAGE_START);

        jPanel1.setLayout(new java.awt.GridLayout(5, 4, 5, 5));
        jPanel1.add(jLabel1);

        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("com/ryanworks/fishery/client/ui/Bundle"); // NOI18N
        jLabel6.setText(bundle.getString("LoginPanel.jLabel1.text")); // NOI18N
        jPanel1.add(jLabel6);

        jLabel2.setText(bundle.getString("LoginPanel.jLabel1.text")); // NOI18N
        jPanel1.add(jLabel2);

        jLabel5.setText(bundle.getString("LoginPanel.jLabel1.text")); // NOI18N
        jPanel1.add(jLabel5);

        jLabel4.setText(bundle.getString("LoginPanel.jLabel1.text")); // NOI18N
        jPanel1.add(jLabel4);

        jLabelUsername.setFont(new java.awt.Font("KaiTi", 0, 48)); // NOI18N
        jLabelUsername.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabelUsername.setText("用户账号:");
        jPanel1.add(jLabelUsername);

        jTextFieldUsername.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        jTextFieldUsername.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldUsername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldUsernameActionPerformed(evt);
            }
        });
        jPanel1.add(jTextFieldUsername);

        jLabel7.setText(bundle.getString("LoginPanel.jLabel1.text")); // NOI18N
        jPanel1.add(jLabel7);

        jLabel8.setText(bundle.getString("LoginPanel.jLabel1.text")); // NOI18N
        jPanel1.add(jLabel8);

        jLabelPassword.setFont(new java.awt.Font("KaiTi", 0, 48)); // NOI18N
        jLabelPassword.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabelPassword.setText("用户密码:");
        jPanel1.add(jLabelPassword);

        jPasswordField.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        jPasswordField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPasswordField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordFieldActionPerformed(evt);
            }
        });
        jPanel1.add(jPasswordField);

        jLabel10.setText(bundle.getString("LoginPanel.jLabel1.text")); // NOI18N
        jPanel1.add(jLabel10);

        jLabel17.setText(bundle.getString("LoginPanel.jLabel1.text")); // NOI18N
        jPanel1.add(jLabel17);

        jLabel16.setText(bundle.getString("LoginPanel.jLabel1.text")); // NOI18N
        jPanel1.add(jLabel16);

        jButtonLogin.setBackground(new java.awt.Color(204, 204, 204));
        jButtonLogin.setFont(new java.awt.Font("KaiTi", 1, 36)); // NOI18N
        jButtonLogin.setText("登入系统");
        jButtonLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLoginActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonLogin);

        jLabel11.setText(bundle.getString("LoginPanel.jLabel1.text")); // NOI18N
        jPanel1.add(jLabel11);

        jLabel12.setText(bundle.getString("LoginPanel.jLabel1.text")); // NOI18N
        jPanel1.add(jLabel12);

        jLabel13.setText(bundle.getString("LoginPanel.jLabel1.text")); // NOI18N
        jPanel1.add(jLabel13);

        jLabel14.setText(bundle.getString("LoginPanel.jLabel1.text")); // NOI18N
        jPanel1.add(jLabel14);

        jLabel15.setText(bundle.getString("LoginPanel.jLabel1.text")); // NOI18N
        jPanel1.add(jLabel15);

        add(jPanel1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLoginActionPerformed
        
        String username = jTextFieldUsername.getText().trim();
        String password = new String(this.jPasswordField.getPassword()).trim();

        if (username.length()==0 || password.length()==0) 
        {
            Toolkit.getDefaultToolkit().beep();
            JOptionPane.showMessageDialog(this, "用户账号或密码错误，请再重新登入。", "核认错误 (1)", JOptionPane.ERROR_MESSAGE);
            this.jPasswordField.requestFocus();
            this.jPasswordField.selectAll();
            
            return;
        }
          
        try 
        {
            ProgressModalDialog dialog = new ProgressModalDialog(this.parent, true, "核认身份中...");
            
            SwingWorker<Void, Void> swingWorker = new SwingWorker<Void, Void>() {
                @Override
                protected Void doInBackground() throws Exception {
                    LoginPanel.this.user = UserDelegate.getInstance().authenticate(username, password);
                    return null;
                }

                @Override
                protected void done() {
                    dialog.dispose();//close the modal dialog
                }
            };

            swingWorker.execute(); // this will start the processing on a separate thread
            SwingUtil.centerDialogOnScreen( dialog );
            
            if (user==null) 
            {
                Toolkit.getDefaultToolkit().beep();
                JOptionPane.showMessageDialog(this, "用户账号或密码错误，请再重新登入。", "核认错误 (2)", JOptionPane.ERROR_MESSAGE);   
                this.jPasswordField.requestFocus();
                this.jPasswordField.selectAll();
            }
            else
            {
                if (this.currentScreen == LoginPanel.MAIN_SCREEN)
                {
                    this.jTextFieldUsername.setText( "" );
                    this.jPasswordField.setText( "" );
                    this.jTextFieldUsername.requestFocus();
                    
                    // Request to switch screen to Inbound Screen
                    ((JFrameMain)this.parent).switchToMainPanel();
                }
            }
        }
        catch (Exception ex) 
        {
            Toolkit.getDefaultToolkit().beep();
            JOptionPane.showMessageDialog(this, "用户账号或密码错误，请再重新登入。", "核认错误 (3)", JOptionPane.ERROR_MESSAGE);
            this.jPasswordField.requestFocus();
            this.jPasswordField.selectAll();
        }
    }//GEN-LAST:event_jButtonLoginActionPerformed

    private void jTextFieldUsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldUsernameActionPerformed
        if ("".equalsIgnoreCase(this.jTextFieldUsername.getText().trim())) 
        {
            // do nothing
        } 
        else
        {
            this.jPasswordField.requestFocus();
        }
    }//GEN-LAST:event_jTextFieldUsernameActionPerformed

    private void jPasswordFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordFieldActionPerformed
        if ("".equalsIgnoreCase(this.jPasswordField.getText().trim()))
        {
            // do nothing
        }
        else
        {
            this.jButtonLogin.doClick();
        }
    }//GEN-LAST:event_jPasswordFieldActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonLogin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabelPassword;
    private javax.swing.JLabel jLabelTitle;
    private javax.swing.JLabel jLabelUsername;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField jPasswordField;
    private javax.swing.JTextField jTextFieldUsername;
    // End of variables declaration//GEN-END:variables
}
