package com.ryanworks.fishery.client.ui;

import javax.swing.JFrame;

/**
 *
 * @author Ryan C
 */
public class MainPanel extends javax.swing.JPanel {

    private final JFrame parent;
    
    /**
     * Creates new form MainPanel
     */
    public MainPanel(JFrame parent) 
    {
        this.parent = parent;
        
        initComponents();
        myInit();
    }
    
    private void myInit()
    {
        // do nothing
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jButtonInbound = new javax.swing.JButton();
        jButtonOutbound = new javax.swing.JButton();
        jButtonControl = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jButtonExit = new javax.swing.JButton();

        setLayout(new java.awt.BorderLayout());

        jLabel1.setBackground(new java.awt.Color(0, 0, 204));
        jLabel1.setFont(new java.awt.Font("KaiTi", 1, 60)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("海春鱼行管理系统");
        jLabel1.setOpaque(true);
        jLabel1.setPreferredSize(new java.awt.Dimension(34, 120));
        add(jLabel1, java.awt.BorderLayout.PAGE_START);

        jPanel1.setLayout(new java.awt.GridBagLayout());

        jButtonInbound.setFont(new java.awt.Font("KaiTi", 1, 48)); // NOI18N
        jButtonInbound.setText("进货");
        jButtonInbound.setPreferredSize(new java.awt.Dimension(200, 150));
        jButtonInbound.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonInboundActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonInbound, new java.awt.GridBagConstraints());

        jButtonOutbound.setFont(new java.awt.Font("KaiTi", 1, 48)); // NOI18N
        jButtonOutbound.setText("出货");
        jButtonOutbound.setPreferredSize(new java.awt.Dimension(200, 150));
        jButtonOutbound.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOutboundActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonOutbound, new java.awt.GridBagConstraints());

        jButtonControl.setFont(new java.awt.Font("KaiTi", 1, 48)); // NOI18N
        jButtonControl.setText("控制台");
        jButtonControl.setPreferredSize(new java.awt.Dimension(200, 150));
        jButtonControl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonControlActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonControl, new java.awt.GridBagConstraints());

        jLabel2.setPreferredSize(new java.awt.Dimension(0, 60));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        jPanel1.add(jLabel2, gridBagConstraints);

        jButtonExit.setFont(new java.awt.Font("KaiTi", 1, 24)); // NOI18N
        jButtonExit.setText("退出系统");
        jButtonExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExitActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        jPanel1.add(jButtonExit, gridBagConstraints);

        add(jPanel1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonInboundActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonInboundActionPerformed
        ((JFrameMain)this.parent).switchToInboundPanel();
    }//GEN-LAST:event_jButtonInboundActionPerformed

    private void jButtonOutboundActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOutboundActionPerformed
        ((JFrameMain)this.parent).switchToOutboundPanel();
    }//GEN-LAST:event_jButtonOutboundActionPerformed

    private void jButtonControlActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonControlActionPerformed
        ((JFrameMain)this.parent).switchToControlPanel();
    }//GEN-LAST:event_jButtonControlActionPerformed

    private void jButtonExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExitActionPerformed
        //((JFrameMain)this.parent).switchToLoginPanel();
        System.exit(1);
    }//GEN-LAST:event_jButtonExitActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonControl;
    private javax.swing.JButton jButtonExit;
    private javax.swing.JButton jButtonInbound;
    private javax.swing.JButton jButtonOutbound;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
