package com.ryanworks.fishery.client.ui.shared;

public class ProgressModalDialog extends javax.swing.JDialog {

    public ProgressModalDialog(java.awt.Frame parent, boolean modal, String status) 
    {
        super(parent, modal);
        initComponents();
                
        this.pack();
        
        this.jLabelStatus.setText(status);
    }
    
    public void setStatus(String status) {
        this.jLabelStatus.setText(status);
    } // .end of setStatus

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelStatus = new javax.swing.JLabel();
        jProgressBar = new javax.swing.JProgressBar();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("请等候 ......");
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(400, 90));
        setResizable(false);

        jLabelStatus.setBackground(new java.awt.Color(51, 51, 51));
        jLabelStatus.setFont(new java.awt.Font("KaiTi", 0, 18)); // NOI18N
        jLabelStatus.setForeground(new java.awt.Color(51, 255, 0));
        jLabelStatus.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelStatus.setText("jLabel1");
        jLabelStatus.setOpaque(true);
        jLabelStatus.setPreferredSize(new java.awt.Dimension(56, 35));
        getContentPane().add(jLabelStatus, java.awt.BorderLayout.PAGE_START);

        jProgressBar.setIndeterminate(true);
        getContentPane().add(jProgressBar, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabelStatus;
    private javax.swing.JProgressBar jProgressBar;
    // End of variables declaration//GEN-END:variables
}
